# Generated by Django 3.0.3 on 2020-05-15 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bouquet',
                'verbose_name_plural': 'Bouquets',
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouquetapp.Bouquet')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('binomial_name', models.CharField(max_length=100)),
                ('longevity_in_days', models.IntegerField()),
                ('bouquets', models.ManyToManyField(through='bouquetapp.BouquetFlower', to='bouquetapp.Bouquet')),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
            },
        ),
        migrations.AddField(
            model_name='bouquetflower',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouquetapp.Flower'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(through='bouquetapp.BouquetFlower', to='bouquetapp.Flower'),
        ),
    ]
